apiVersion: batch/v1
kind: CronJob
metadata:
  name: sig-node-prs
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sig-node-prs
            image: gcr.io/apmtips/sig-node-prs:latest
          restartPolicy: OnFailure
